### ISSUE TITLE
non-integer ID input results in SQL parse 500 response

### ISSUE THREAD

**Issue by clint-tseng** [opendatakit/central-backend#135]
as mentioned by akshay on slack:

```
curl -X DELETE \
  http://localhost:8383/v1/field-keys/324fdsd \
  -H 'Authorization: Bearer <cut>'
```

results in 

```
{ error: invalid input syntax for integer: "324fdsd"
    at Connection.parseE (F:\Akshay\wGit\central-backend\node_modules\pg\lib\connection.js:545:11)
    at Connection.parseMessage (F:\Akshay\wGit\central-backend\node_modules\pg\lib\connection.js:370:19)
    at Socket.<anonymous> (F:\Akshay\wGit\central-backend\node_modules\pg\lib\connection.js:113:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
  name: 'error',
  length: 97,
  severity: 'ERROR',
  code: '22P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'numutils.c',
  line: '106',
  routine: 'pg_atoi' }
```

this should be solvable with an addition for `22P02` to the sql error translation layer.

**Comment by akshay-ap** [comment]
I would like to work on it.

**Comment by akshay-ap** [comment]
Same error is thrown while updating user details.
```
curl -X PATCH \
  http://localhost:8383/v1/users/8aa \
  -H 'Authorization: Bearer <token> \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -d '{
	"email" : "email@emial.com",
	"displayName" : "username"
}'
```
