### ISSUE TITLE
CSV .zip download error

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/central-backend#255]
I'm noticing error messages for a form that @florianm uploaded to the Central sandbox:

https://sandbox.central.opendatakit.org/#/projects/1/forms/build_Untitled-Form_1540747842/submissions

The request to `….schema.json` returns a Problem with the message "Completely unhandled exception: schema is not iterable". Also, attempting to download the CSV .zip file returns a Problem with the message "Completely unhandled exception: Cannot read property 'push' of undefined".

**Comment by florianm** [comment]
Hi Matt, could this form belong to a different Florian? (lugaliki org)

My projects on the sandbox are labelled with ruODK. My activity in project #1 would stem from very early test drives.

**Comment by matthew-white** [comment]
Ah yes, you're right — sorry about that!

**Comment by issa-tseng** [comment]
@matthew-white i don't repro this as of the v0.8 changes. do you see the same?

**Comment by matthew-white** [comment]
Yes! :+1: I first tried reproducing the issue after checking out the `v0.7.0` commit. I was able to do so after uploading this form definition: I saw error messages for `…/schema.json` and `…/submissions.csv.zip`. (Note that I only saw the error message for `…/schema.json` after specifying `?flatten=true`.) I then checked out `master` and didn't see error messages for `…/fields` or `…/submissions.csv.zip`. (I used `curl` rather than Frontend for these requests.)

By the way, I noticed that after checking out `v0.7.0` and seeing the error messages, I had to control+Z to stop the server. I also saw the following error message:

```
Unhandled rejection TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at node_modules/knex/lib/client.js:345:17
    at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
```

**Comment by issa-tseng** [comment]
closing this as it will resolve as of v0.8.
